# -*- coding: utf-8 -*-
##
##
## This dictionary is used for ICTP sponsors/co-sponsors logo generation

# Recognized SPONSORS
available_sponsors = {
"ictp":{"url":"http://www.ictp.it/","country":"italy","title":""},        
"infn":{"url":"http://www.infn.it","country":"italy","title":""}, 
"(nim)":{"url":"http://www.nano-initiative-munich.de/","country":"germany","title":""}, 
"(cens)":{"url":"http://www.cens.de/","country":"germany","title":""}, 
"sissa":{"url":"http://www.sissa.it/","country":"italy","title":""}, 
"twas":{"url":"http://www.twas.org/","country":"italy","title":""}, 
"(elettra)":{"url":"http://www.elettra.trieste.it/","country":"italy","title":""}, 
"sesame":{"url":"http://www.sesame.org.jo/","country":"","title":""}, 
"infm":{"url":"http://www.cnr.it/sitocnr/IlCNR/Organizzazione/RiformadelCNR/EnticonfluitiCNR/Infm.html","country":"italy","title":""}, 
"volkswagenstiftung":{"url":"http://www.volkswagenstiftung.de/","country":"germany","title":""}, 
"iisi":{"url":"http://www.cs.cornell.edu/annual_report/00-01/www.cis.cornell.edu/iisi","country":"usa","title":""}, 
"cornell university":{"url":"http://www.cornell.edu/","country":"usa","title":""}, 
"european commission":{"url":"http://ec.europa.eu/index_en.htm","country":"europe","title":""}, 
"iaea":{"url":"http://iaea.org/","country":"austria","title":""}, 
"forschungsgemeinschaft":{"url":"http://www.dfg.de/","country":"germany","title":""}, 
"nigerian national universities commission":{"url":"http://www.nuc.edu.ng/","country":"nigeria","title":""}, 
"international telecommunication union":{"url":"http://www.itu.int/","country":"switzerland","title":""}, 
"(ibro)":{"url":"http://ibro.info/","country":"","title":""}, 
"icgeb":{"url":"http://www.icgeb.org/","country":"italy","title":""}, 
"cnpq":{"url":"http://www.cnpq.br/","country":"brazil","title":""}, 
"kfas":{"url":"http://www.kfas.org/","country":"kuwait","title":""}, 
"ics-unido":{"url":"http://institute.unido.org/ICS_UNIDO.html","country":"austria","title":""}, 
"absoft corporation":{"url":"http://www.absoft.com/","country":"usa","title":""}, 
"(nsf)":{"url":"http://www.nsf.gov/","country":"usa","title":""}, 
"(onr)":{"url":"http://www.onr.navy.mil/","country":"usa","title":""}, 
"tribhuvan university":{"url":"http://tribhuvan-university.edu.np/","country":"nepal","title":""}, 
"royal nepal academy of science and technology":{"url":"http://www.nast.org.np/","country":"nepal","title":""}, 
"(unu)":{"url":"http://unu.edu/","country":"japan","title":""}, 
"(epic)":{"url":"http://www.rish.kyoto-u.ac.jp/radar-group/epic/","country":"japan","title":""}, 
"scostep":{"url":"http://www.yorku.ca/scostep/","country":"canada","title":""}, 
"sparc":{"url":"http://www.sparc-climate.org/","country":"switzerland","title":""}, 
"icma":{"url":"http://www-mete.kugi.kyoto-u.ac.jp/project/ICMA/","country":"japan","title":""}, 
"iamas":{"url":"http://www.iamas.org/","country":"germany","title":""}, 
"(esa)":{"url":"http://www.esa.int/ESA","country":"france","title":""}, 
"(nasa)":{"url":"http://www.nasa.gov/","country":"usa","title":""}, 
"sils":{"url":"http://www.synchrotron-radiation.it/index.php/en/","country":"italy","title":""}, 
"scuola normale superiore":{"url":"http://www.sns.it/en/","country":"italy","title":""}, 
"istituto nazionale di geofisica":{"url":"http://www.ingv.it/","country":"italy","title":""}, 
"cnr":{"url":"http://cnr.it/","country":"italy","title":""}, 
"university of trieste":{"url":"http://www.units.it/","country":"italy","title":""}, 
"ogp":{"url":"http://cpo.noaa.gov/","country":"usa","title":""}, 
"wmo":{"url":"http://www.wmo.int/","country":"usa","title":""}, 
"ministero dell'istruzione":{"url":"http://www.istruzione.it/","country":"italy","title":""}, 
"beijer international institute":{"url":"http://www.beijer.kva.se/","country":"sweden","title":""}, 
"feem":{"url":"http://www.feem.it/","country":"italy","title":""}, 
"(ico)":{"url":"http://www.ico.edu/","country":"usa","title":""}, 
"(osa)":{"url":"http://www.osa.org/","country":"usa","title":""}, 
"(spie)":{"url":"http://spie.org/","country":"usa","title":""}, 
"(cei)":{"url":"http://www.cei.int/","country":"italy","title":""}, 
"nitda":{"url":"http://www.nitda.gov.ng/","country":"nigeria","title":""}, 
"miur":{"url":"http://www.istruzione.it/","country":"italy","title":""}, 
"university of genoa":{"url":"http://www.unige.it/","country":"italy","title":""}, 
"quacs":{"url":"http://www.weizmann.ac.il/chemphys/gershon/quacs/quacs.html","country":"israel","title":""}, 
"icts":{"url":"http://english.ict.cas.cn/","country":"china","title":""}, 
"italian ministry for education":{"url":"http://www.istruzione.it/","country":"italy","title":""}, 
"tamu rf":{"url":"http://rf.tamus.edu/","country":"usa","title":""}, 
"onrg":{"url":"http://www.onr.navy.mil/en/Science-Technology/ONR-Global.aspx","country":"usa","title":""}, 
"i2cam":{"url":"http://icam-i2cam.org/","country":"usa","title":""}, 
"thorpex":{"url":"http://www.wmo.int/pages/prog/arep/wwrp/new/THORPEXProjectsActivities.html","country":"usa","title":""}, 
"wcrp":{"url":"http://www.wcrp-climate.org/","country":"switzerland","title":""}, 
"icmr":{"url":"http://www.icmr.ucsb.edu/","country":"usa","title":""}, 
"owls":{"url":"http://www.campus.uni-muenster.de/fileadmin/einrichtung/cebop/owls/info.html","country":"germany","title":""}, 
"(inaf)":{"url":"http://www.ts.astro.it/inaf","country":"italy","title":""}, 
"nswp":{"url":"http://www.nswp.gov/nswp_index.htm","country":"USA","title":""}, 
"max-planck-institut":{"url":"http://www.mpg.de/en","country":"Germany","title":""}, 
"johns hopkins university":{"url":"http://www.jhu.edu/","country":"USA","title":""}, 
"wellcome trust":{"url":"http://www.wellcome.ac.uk/index.htm","country":"UK","title":""}, 
"(nec)":{"url":"http://www.nec-labs.com/","country":"USA","title":""}, 
"universita' degli studi di milano":{"url":"http://www.unimi.it/","country":"Italy","title":""}, 
"(inasp)":{"url":"http://www.inasp.info/","country":"UK","title":""}, 
"national natural science foundation of china":{"url":"http://www.nsfc.gov.cn/publish/portal1/","country":"China","title":""}, 
"(cas)":{"url":"http://english.cas.cn/","country":"China","title":""}, 
"ministero dell'ambiente":{"url":"http://www.minambiente.it/","country":"Italy","title":""}, 
"(esf)":{"url":"http://www.esf.org/home.html","country":"France","title":""}, 
"(siof)":{"url":"http://www.siof-ottica.it/sito/","country":"Italy","title":""}, 
"national science foundation of china":{"url":"http://www.nsfc.gov.cn/publish/portal1/","country":"China","title":""}, 
"national natural science foundation of china":{"url":"http://www.nsfc.gov.cn/publish/portal1/","country":"China","title":""}, 
"university of surrey":{"url":"http://www.surrey.ac.uk/","country":"UK","title":""}, 
"(eos)":{"url":"http://www.myeos.org/","country":"Finland","title":""}, 
"eu-nest":{"url":"http://cordis.europa.eu/nest/","country":"","title":""}, 
"iaea":{"url":"http://www.iaea.org/","country":"Austria","title":""}, 
"international society of electrochemistry'":{"url":"http://www.ise-online.org/","country":"Switzerland","title":""}, 
"nissan motor":{"url":"http://www.nissan-global.com/EN/index.html","country":"Japan","title":""}, 
"general motors corporation":{"url":"http://www.gm.com/","country":"USA","title":""}, 
"ncbs":{"url":"http://www.ncbs.res.in/","country":"India","title":""}, 
"tifr":{"url":"http://www.tifr.res.in/index.php/en/","country":"India","title":""}, 
"(unam)":{"url":"http://www.unam.mx/","country":"Mexico","title":""}, 
"cimpa":{"url":"http://www.cimpa-icpam.org/","country":"France","title":""}, 
"(cmi)":{"url":"http://www.claymath.org/","country":"USA","title":""}, 
"msri":{"url":"http://www.msri.org/web/msri","country":"USA","title":""}, 
"(spider)":{"url":"http://spidercenter.org/","country":"Sweden","title":""}, 
"ieee-sl":{"url":"http://sites.ieee.org/","country":"USA ","title":""}, 
"bdt":{"url":"http://www.itu.int/en/Pages/default.aspx","country":"Switzerland","title":""}, 
"university of massachusetts":{"url":"http://www.massachusetts.edu/index.html","country":"USA","title":""}, 
"pacific institute of theoretical physics":{"url":"http://pitp.physics.ubc.ca/","country":"Canada","title":""}, 
"wna":{"url":"http://www.world-nuclear.org/","country":"UK","title":""}, 
"varian medical systems":{"url":"http://www.varian.com/","country":"USA","title":""}, 
"aapm":{"url":"https://www.aapm.org/default.asp","country":"USA","title":""}, 
"efomp":{"url":"http://www.efomp.org/","country":"UK","title":""}, 
"computer engineering":{"url":"http://www.e4company.com/","country":"Italy","title":""}, 
"eurotech":{"url":"http://www.eurotech.com/it/","country":"Italy","title":""}, 
"ibm":{"url":"http://www.ibm.com/us/en/","country":"USA","title":""}, 
"spring firm":{"url":"http://www.springfirm.it/home/index.html","country":"Italy","title":""}, 
"(epri)":{"url":"http://www.epri.com/Pages/Default.aspx","country":"USA","title":""}, 
"noaa":{"url":"http://www.noaa.gov/","country":"USA","title":""}, 
"(pages)":{"url":"http://www.pages-igbp.org/","country":"Switzerland","title":""}, 
"clivar":{"url":"http://www.clivar.org/","country":"The Netherlands","title":""}, 
"nithep":{"url":"http://www.nithep.ac.za/","country":"South Africa","title":""}, 
"chpc":{"url":"http://www.chpc.ac.za/","country":"South Africa","title":""}, 
"mcc":{"url":"http://www.mcc.uiuc.edu/","country":"USA","title":""}, 
"area science park":{"url":"http://www.area.trieste.it/opencms/opencms/area/en/","country":"Italy","title":""}, 
"(iop)":{"url":"http://www.iop.org/","country":"UK","title":""}, 
"(aps)":{"url":"http://www.aps.org/","country":"USA","title":""}, 
"iupap":{"url":"http://iupap.org/","country":"UK","title":""}, 
"nmc":{"url":"http://nmcabuja.org/","country":"Nigeria","title":""}, 
"fortim":{"url":"http://www.ebsu-edu.net/","country":"Nigeria","title":""}, 
"psi-k":{"url":"http://www.psi-k.org/","country":"UK","title":""}, 
"cecam":{"url":"http://www.cecam.org/","country":"Switzerland ","title":""}, 
"(mit)":{"url":"http://www.rle.mit.edu/mit-harvard-center-for-ultracold-atoms/","country":"USA","title":""}, 
"(cua)":{"url":"http://cuaweb.mit.edu/","country":"USA","title":""}, 
"radcal":{"url":"http://www.radcal.com/","country":"USA","title":""}, 
"rti electronics":{"url":"http://www.rti.se/","country":"Sweden","title":""}, 
"ptw":{"url":"http://www.ptw.de/home_start.html?&no_cache=1","country":"Germany","title":""}, 
"unfors":{"url":"http://www2.unfors.se/index.php?catid=12","country":"Sweden","title":""}, 
"gennetec":{"url":"http://gennetec.csregistry.org/tiki-index.php?page=HomePage","country":"France","title":""}, 
"(cola)":{"url":"http://www.iges.org/cola.html","country":"USA","title":""}, 
"iavcei":{"url":"http://www.iavcei.org/","country":"","title":""}, 
"iaspei":{"url":"http://www.iaspei.org/","country":"","title":""}, 
"unavco":{"url":"http://www.unavco.org/","country":"USA","title":""}, 
"usaid":{"url":"http://www.usaid.gov/","country":"USA","title":""}, 
"stfc":{"url":"https://www.stfc.ac.uk/home.aspx","country":"UK","title":""}, 
"(enen)":{"url":"http://www.enen-assoc.org/","country":"France","title":""}, 
"nvidia":{"url":"http://www.nvidia.com/page/home.html","country":"USA","title":""}, 
"(fanas)":{"url":"http://www.esf.org/coordinating-research/eurocores/completed-programmes/fanas.html","country":"","title":""}, 
"conicyt":{"url":"http://www.conicyt.cl/","country":"Chile","title":""}, 
"(iut)":{"url":"http://www.iut.ac.ir/en/","country":"Iran","title":""}, 
"universidad de antioquia":{"url":"http://www.udea.edu.co/portal/page/portal/portal","country":"Colombia","title":""}, 
"universidad pontificia bolivariana":{"url":"http://www.upb.edu.co/portal/page?_pageid=954,1&_dad=portal&_schema=PORTAL","country":"Colombia","title":""}, 
"universidad de los andes":{"url":"http://www.uniandes.edu.co/","country":"Colombia","title":""}, 
"cpn/senamhi":{"url":"http://www.senamhi.gob.pe/_1500.php?p=1500&idNota=02_110406_01","country":"Peru","title":""}, 
"samarkand state university":{"url":"http://www.university-directory.eu/Uzbekistan/Samarkand-State-University.html#.U6P4Z6hf7QR","country":"Uzbekistan","title":""}, 
"national university of uzbekistan":{"url":"http://nuu.uz/","country":"Uzbekistan","title":""}, 
"(imu)":{"url":"http://www.mathunion.org/","country":"","title":""}, 
"fapesp":{"url":"http://www.fapesp.br/","country":"Brazil","title":""}, 
"(capes)":{"url":"http://www.capes.gov.br/","country":"Brazil","title":""}, 
"universidad federal do abc":{"url":"http://www.ufabc.edu.br/","country":"Brazil","title":""}, 
"u.s. office of naval research":{"url":"http://www.onr.navy.mil/","country":"USA","title":""}, 
"u.s. army research office":{"url":"http://www.arl.army.mil/www/default.cfm?page=29","country":"USA","title":""}, 
"enel- green power":{"url":"http://www.enelgreenpower.com/it-IT/","country":"Italy","title":""}, 
"(iga)":{"url":"http://www.geothermal-energy.org/","country":"Germany","title":""}, 
"(ugi)":{"url":"http://www.unionegeotermica.it/","country":"Italy","title":""}, 
"eu-indiagrid":{"url":"http://www.euindiagrid.eu/","country":"","title":""}, 
"(ancs)":{"url":"http://www.research.ro/","country":"Romania","title":""}, 
"ifin-hh":{"url":"http://www.nipne.ro/","country":"Romania","title":""}, 
"(ulb)":{"url":"http://www.ulbsibiu.ro/en/","country":"Romania","title":""}, 
"us national academy of science":{"url":"http://www.nasonline.org/","country":"USA","title":""}, 
"ensf":{"url":"http://www.ensf-ngo.org/new/index.php","country":"Italy","title":""}, 
"international association of geodesy":{"url":"http://www.iag-aig.org/","country":"Germany","title":""}, 
"nsrc":{"url":"https://www.nsrc.org/","country":"USA","title":""}, 
"boston college":{"url":"http://www.bc.edu/","country":"USA","title":""}, 
"(icam)":{"url":"http://icam-i2cam.org/","country":"USA","title":""}, 
"intel-biomat":{"url":"http://www.esf.org/home.html","country":"France","title":""}, 
"(riken)":{"url":"http://www.asi.riken.jp/en/","country":"Japan","title":""}, 
"arnold sommerfeld center for theoretical physics":{"url":"http://www.en.physik.uni-muenchen.de/faculty/centers/asc/index.html","country":"Germany","title":""}, 
"(lmu)":{"url":"http://www.cens.de/","country":"Germany","title":""}, 
"nanosystems initiative munich":{"url":"https://www.en.uni-muenchen.de/about_lmu_alt/excellence_initiative/clusters/nim/index.html","country":"Germany","title":""}, 
"yale university":{"url":"http://www.yale.edu/","country":"USA","title":""}, 
"air force office of scientific research":{"url":"http://www.wpafb.af.mil/afrl/afosr/","country":"USA","title":""}, 
"eur-oceans":{"url":"http://www.eur-oceans.eu/","country":"France","title":""}, 
"soteria":{"url":"http://soteria-space.eu/","country":"","title":""}, 
"ipm-grid":{"url":"http://cagrid.ipm.ac.ir/","country":"Iran","title":""}, 
"apctp":{"url":"https://www.apctp.org/main/","country":"Korea","title":""}, 
"iqoqi":{"url":"http://iqoqi.at/en/","country":"Austria","title":""}, 
"(start)":{"url":"http://start.org/","country":"USA","title":""}, 
"adglass":{"url":"http://www.adglass.eu/","country":"Germany","title":""}, 
"intelbiomat":{"url":"http://www.esf.org/index.php?id=4929","country":"France","title":""}, 
"icam-12cam":{"url":"http://icam-i2cam.org/","country":"USA","title":""}, 
"alfateh university":{"url":"http://uot.edu.ly/","country":"Libya","title":""}, 
"(nasr)":{"url":"http://www.nasr.ly/nasr2012/index.php/2012-03-24-22-02-27","country":"Libya","title":""}, 
"unesco":{"url":"http://en.unesco.org/","country":"France","title":""}, 
"esteco":{"url":"http://www.esteco.com/","country":"Italy","title":""}, 
"cnr-iom":{"url":"http://www.iom.cnr.it/","country":"Italy","title":""}, 
"university of buenos aires":{"url":"http://www.uba.ar/","country":"Argentina","title":""}, 
"alexander-von-humboldt foundation":{"url":"http://www.humboldt-foundation.de/web/home.html","country":"Germany","title":""}, 
"association pour la promotion scientifique de l'afrique":{"url":"http://www.scienceafrique.fr/","country":"France","title":""}, 
"european physical society":{"url":"http://www.eps.org/","country":"France","title":""}, 
"international union of pure and applied physics":{"url":"http://iupap.org/","country":"UK","title":""}, 
"(aims)":{"url":"http://www.aims.ac.za/","country":"South Africa","title":""}, 
"perimeter institute":{"url":"https://www.perimeterinstitute.ca/","country":"Canada","title":""}, 
"royal society":{"url":"https://royalsociety.org/","country":"UK","title":""}, 
"ska africa":{"url":"http://www.ska.ac.za/","country":"South Africa","title":""}, 
"anna university":{"url":"http://www.annauniv.edu/","country":"India","title":""}, 
"(prace)":{"url":"http://www.prace-ri.eu/","country":"Belgium","title":""}, 
"exact lab":{"url":"http://www.exact-lab.it/","country":"Italy","title":""}, 
"american institute of physics":{"url":"http://www.aip.org/","country":"USA","title":""}, 
"iubmb":{"url":"http://www.iubmb.org/","country":"Canada","title":""}, 
"douglas instruments":{"url":"http://www.douglas.co.uk/","country":"UK","title":""}, 
"italian ministry of foreign affairs":{"url":"http://www.esteri.it/mae/en","country":"Italy","title":""}, 
"european science foundation":{"url":"http://www.esf.org/","country":"France","title":""}, 
"scuola normale superiore di pisa":{"url":"http://www.sns.it/","country":"Italy","title":""}, 
"iugg":{"url":"http://www.iugg.org/","country":"Germany","title":""}, 
"iitm":{"url":"http://www.tropmet.res.in/","country":"India","title":""}, 
"intel biomat":{"url":"http://www.esf.org/home.html","country":"France","title":""}, 
"university of tokyo":{"url":"http://www.u-tokyo.ac.jp/en/","country":"Japan","title":""}, 
"nanjing university":{"url":"http://www.nju.edu.cn/html/eng/1.html","country":"China","title":""}, 
"snn adaptive intelligence":{"url":"http://www.snn.ru.nl/v2/","country":"The Netherlands","title":""}, 
"university of nijmegen":{"url":"http://www.ru.nl/english/","country":"The Netherlands","title":""}, 
"(anl)":{"url":"http://www.anl.gov/","country":"USA","title":""}, 
"india sri lanka foundation":{"url":"http://www.hcicolombo.org/page/display/16","country":"Sri Lanka","title":""}, 
"indian national science academy":{"url":"http://www.insaindia.org/","country":"India","title":""}, 
"(csir)":{"url":"http://www.csir.res.in/","country":"India","title":""}, 
"vigyan prasar":{"url":"http://www.vigyanprasar.gov.in/index.asp","country":"India","title":""}, 
"(dst)":{"url":"http://dst.gov.in/","country":"India","title":""}, 
"dskc":{"url":"http://www.mirandahouse.ac.in/DSKC/","country":"India","title":""}, 
"miranda house":{"url":"http://www.mirandahouse.ac.in/MirandaHouse/","country":"India","title":""}, 
"cbpf":{"url":"http://portal1.cbpf.br/","country":"Brazil","title":""}, 
"(claf)":{"url":"http://www.claffisica.org.br/","country":"Brazil","title":""}, 
"faperj":{"url":"http://www.faperj.br/","country":"Brazil","title":""}, 
"american physical society":{"url":"http://www.aps.org/","country":"USA","title":""}, 
"beijing computational science research center":{"url":"http://www.csrc.ac.cn/","country":"China","title":""}, 
"chepkoilel university college":{"url":"http://www.mu.ac.ke/index.php/quality-assurance/103-schools-campuses-and-colleges/190-chep-university-college","country":"Kenya","title":""}, 
"(icsu)":{"url":"http://www.icsu.org/","country":"France","title":""}, 
"tribhuvan university":{"url":"http://tribhuvan-university.edu.np/","country":"Nepal","title":""}, 
"undp/aap project":{"url":"http://www.undp.org/content/undp/en/home/ourwork/environmentandenergy/projects_and_initiatives/aap/","country":"USA","title":""}, 
"itn cqom":{"url":"http://www.cqom-itn.net/","country":"","title":""}, 
"itu/bdt":{"url":"http://www.itu.int/en/Pages/default.aspx","country":"Switzerland","title":""}, 
"(epl)":{"url":"http://iopscience.iop.org/0295-5075","country":"","title":""}, 
"friuli venezia giulia":{"url":"http://www.regione.fvg.it/rafvg/cms/RAFVG/","country":"Italy","title":""}, 
"(breuds)":{"url":"http://www2.imperial.ac.uk/~jswlamb/DynamIC/BREUDS/","country":"Brazil","title":""}, 
"(ewm)":{"url":"http://www.europeanwomeninmaths.org/","country":"","title":""}, 
"(indam)":{"url":"http://www.altamatematica.it/","country":"Italy","title":""}, 
"gnampa":{"url":"http://www.altamatematica.it/gnampa/","country":"Italy","title":""}, 
"gnfm":{"url":"http://www.altamatematica.it/gnfm/","country":"Italy","title":""}, 
"university of torino":{"url":"http://www.unito.it/unitoWAR/page/unito/home_en/P34609334691252602657885","country":"Italy","title":""}, 
"university of l'aquila":{"url":"http://www.univaq.it/","country":"Italy","title":""}, 
"aston institute of photonic technologies":{"url":"http://www.aston.ac.uk/eas/research/groups/photonics/","country":"UK","title":""}, 
"european laboratory for non-linear spectroscopy":{"url":"http://lens.unifi.it/","country":"Italy","title":""}, 
"novosibirsk state university":{"url":"http://www.nsu.ru/exp/index.jz?lang=en","country":"Russia","title":""}, 
"institute of automation and electrometry of russian academy of science":{"url":"http://www.iae.nsk.su/index.php/en/","country":"Russia","title":""}, 
"international institute for complex adaptive matter":{"url":"http://icam-i2cam.org/","country":"USA","title":""}, 
"consorzio per la fisica":{"url":"http://www.consorzio-fisica-trieste.it/","country":"Italy","title":""}, 
"comune of trieste":{"url":"http://www.retecivica.trieste.it/","country":"Italy","title":""}, 
"degli studi di trieste":{"url":"http://www.units.it/","country":"Italy","title":""}, 
"go fast project":{"url":"http://www.gofastproject.eu/","country":"Italy","title":""}, 
"(erc)":{"url":"http://erc.europa.eu/","country":"Belgium","title":""}, 
"swiss nanoscience institute":{"url":"http://www.nanoscience.ch/nccr/","country":"Switzerland","title":""}, 
"university of basel":{"url":"http://www.unibas.ch/index.cfm?o_lang_id=2","country":"Switzerland","title":""}, 
"(gmu)":{"url":"http://www.gmu.edu/","country":"USA","title":""}, 
"(nus)":{"url":"http://www.nus.edu.sg/","country":"Singapore","title":""}, 
"graphene research centre":{"url":"http://graphene.nus.edu.sg/","country":"Singapore","title":""}, 
"physics of novel electronics":{"url":"http://phyne.spms.ntu.edu.sg/","country":"Singapore","title":""}, 
"office of naval research global":{"url":"http://www.onr.navy.mil/en/Science-Technology/ONR-Global.aspx","country":"USA","title":""}, 
"centro internacional de fisica":{"url":"http://www.cif.org.co/","country":"Colombia","title":""}, 
"craag":{"url":"http://www.craag.dz/","country":"Algeria","title":""}, 
"usthb":{"url":"http://www.usthb.dz/","country":"Algeria","title":""}, 
"(naget)":{"url":"http://naget.ictp.it/","country":"Italy","title":""}, 
"quantum-espresso":{"url":"http://www.quantum-espresso.org/","country":"UK","title":""}, 
"key laboratory of computational physical sciences":{"url":"http://www.cps.fudan.edu.cn/EN/","country":"China","title":""}, 
"(unisa)":{"url":"http://www.unisa.ac.za/default.html","country":"South Africa","title":""}, 
"nrf":{"url":"http://www.nrf.ac.za/","country":"South Africa","title":""}, 
"(afc)":{"url":"http://www.africanlasercentre.org/?p=7460","country":"South Africa","title":""}, 
"french embassy":{"url":"http://www.ambafrance-rsa.org/","country":"South Africa","title":""}, 
"(usu)":{"url":"http://www.uniud.it/","country":"Italy","title":""}, 
"nanoafnet":{"url":"http://www.nanoafnet.tlabs.ac.za/","country":"South Africa","title":""}, 
"south african institute of physics":{"url":"http://www.saip.org.za/","country":"South Africa","title":""}, 
"ansole":{"url":"http://www.ansole.org/","country":"Austria","title":""}, 
"ithemba":{"url":"http://www.tlabs.ac.za/","country":"South Africa","title":""}, 
"republique francaise":{"url":"http://www.diplomatie.gouv.fr/en/","country":"France","title":""}, 
"(alc)":{"url":"http://www.africanlasercentre.org/?p=7460","country":"South Africa","title":""}, 
"(vast)":{"url":"http://www.vast.ac.vn/en/","country":"Vietnam","title":""}, 
"vnuh":{"url":"http://e.uet.vnu.edu.vn/","country":"Vietnam","title":""}, 
"nru hse":{"url":"http://www.hse.ru/en/","country":"Russia","title":""}, 
"(miras)":{"url":"http://www.mi.ras.ru/?l=1","country":"Russia","title":""}, 
"scienomics":{"url":"http://scienomics.com/","country":"France","title":""}, 
"pns":{"url":"http://www.pns-state.net/en-us/","country":"USA","title":""}, 
"moes":{"url":"http://dod.nic.in/","country":"India","title":""}, 
"cheikh anta diop":{"url":"http://www.ucad.sn/","country":"Senegal","title":""}, 
"nlaga":{"url":"http://nlaga-simons.ucad.sn/","country":"Senegal","title":""}, 
"simons foundation":{"url":"http://www.simonsfoundation.org/","country":"USA","title":""}, 
"recherche scientifique":{"url":"http://www.recherche.gouv.sn/","country":"Senegal","title":""}, 
"(aust)":{"url":"http://aust-abuja.org/","country":"Nigeria","title":""}, 
"thomas young centre":{"url":"http://www.thomasyoungcentre.org/","country":"UK","title":""}, 
"tsm":{"url":"http://www3.imperial.ac.uk/theoryandsimulationofmaterials","country":"UK","title":""}, 
"imperial college":{"url":"http://www3.imperial.ac.uk/","country":"UK","title":""}, 
"school of mathematical sciences":{"url":"http://en.ustc.edu.cn/","country":"China","title":""}, 
"(ivic)":{"url":"http://www.ivic.gob.ve/","country":"Venezuela","title":""}, 
"fonacit":{"url":"http://www.fonacit.gov.ve/","country":"Venezuela","title":""}, 
"cinvestav":{"url":"http://www.cinvestav.mx/","country":"Mexico","title":""}, 
"(apsa)":{"url":"http://www.scienceafrique.fr/","country":"France","title":""}, 
"robert bosch foundation":{"url":"http://www.bosch-stiftung.de/content/language2/html/index.asp","country":"Germany","title":""}, 
"(ugc)":{"url":"www.ugc.ac.in/","country":"India","title":""}, 


# ONLY TITLES from here.... no logos

"(cec)":{"url":"http://www.cnr.it","country":"Italy","title":"Gruppo Nazionale Elettronica Quantistica e Plasmi del CNR"}, 
"eoard":{"url":"","country":"usa","title":"European Office of Aerospace Research and Development of the USA"}, 
"lammps":{"url":"https://sites.google.com/site/akohlmey/news-and-announcements/lammpsusersanddevelopersworkshopandsymposiumictp","country":"Italy","title":"LAMMPS Users and Developers Workshop and Symposium"}, 
"consortium of the americas for interdisciplinary science":{"url":"http://consortium.unm.edu/","country":"USA","title":"Consortium of the Americas for Interdisciplinary Science"}, 
"yaounde":{"url":"","country":"","title":"Agence Universitaire de la Francophonie"},
"micinn":{"url":"","country":"","title":"Spanish Ministry of Science and Innovation"},
"pronex":{"url":"","country":"","title":"Pronex-Dynamical Systems"},
"dyneurbraz":{"url":"http://lmba.math.univ-brest.fr/perso/renaud.leplaideur/dyneurbraz.html","country":"","title":"DynEurBraz"},
"modphysfrict":{"url":"","country":"","title":"Modeling the Physics of (Nano) Friction"},
"(miras)":{"url":"http://www.mi.ras.ru/?l=1","country":"Russia","title":"Steklov Mathematical Institute of the Russian Academy of Science"},
"recherchescientifique":{"url":"http://www.recherche.gouv.sn/","country":"Senegal","title":"Minist&egrave;re de l&apos;Enseignement sup&eacute;rieur et de la Recherche"},
"university of science and technology of china":{"url":"en.ustc.edu.cn/","country":"China","title":""},
"svmf":{"url":"","country":"","title":"Venezuelan Society of Fluid Mechanics"}, 
"exystence":{"url":"http://www.complexityscience.org","country":"","title":"EXYSTENCE EC Network of Excellence"},
}
